### ISSUE TITLE
New reporter for New relic

### ISSUE THREAD

**Issue by dav-m85** [liip/LiipMonitorBundle#104]
We're using New Relic as our platform health backend. We're currently dupicating the code for checks and NR clients. It would be nice to have a new-relic reporter to merge this code.

What's your opinion on this ?

**Comment by kbond** [comment]
Sounds interesting to me!

**Comment by kbond** [comment]
One thing to note is additional reporters should be added to https://github.com/zendframework/ZendDiagnostics/tree/master/src/ZendDiagnostics/Runner/Reporter

**Comment by dav-m85** [comment]
:+1:
