### ISSUE TITLE
Cache mechanism for long running checks

### ISSUE THREAD

**Issue by dav-m85** [liip/LiipMonitorBundle#105]
Some checks we're using at lafourchette are really long to run, or relie on data which is not present at all times. A way of dealing with it would be to introduce a caching mechanism that would retrieve the cache data, and if not fresh initiate the recomputing of it.

Ideally, we would have:
* configurable cache timeframe
* anti dog-stomping mechanism
* forked computing process

**Comment by kbond** [comment]
Seems like something that should be done in the checks themselves as it is probably very use case specific...

But, perhaps an `AbstractCacheCheck` might be an idea, I think that would have to be added to https://github.com/zendframework/ZendDiagnostics though.

To me, it might be a bit confusing to run your check and see success but not really know if it is a success... sort of defeats the purpose.

**Comment by lsmith77** [comment]
yeah .. sounds pretty specific in the sense that I would expect another library to be used for such needs.
