### ISSUE TITLE
Make check_symfony2.py compatible with nagiosplugin 1.2

### ISSUE THREAD

**Issue by albanduval** [liip/LiipMonitorBundle#109]
Hi,

Great work on this bundle :)

As the nagiosplugin < 1.0.0 is not that easy to install anymore, it would be really nice to have a python script working with the current version (1.2 as I speak).
Maybe a simple script that would not need any library would be even better... 

I could try to code it myself if there is a chance to merge it back on your repository.

Thanks again for this useful bundle,
Alban.

**Comment by lsmith77** [comment]
we are open to merge it .. so please try and create a PR
