### ISSUE TITLE
HealthCheckCommand with neither RawConsoleReporter nor ConsoleReporter

### ISSUE THREAD

**Issue by DrSchimke** [liip/LiipMonitorBundle#111]
I need a way to start the health check command, using a customized reporter, such that not `RawConsoleReporter` and  not `ConsoleReporter` produce any output.

Or, eventually, is there a way to append some string (e.g. duration time) at the end of each line of check-output. (Problem is, both mentioned reporters use writeln in the end.)

How a solution to my problem could look like, if I want to avoid any BC breaks?

**Comment by arosslau** [comment]
Our Purpose is to add ["Nagios Performance Data"](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/perfdata.html) to each check-result which has have a syntax like that:

```
DNS OK: 0.011 seconds response time. vs01.rz02.postcon.intern returns x.xxx.xx.x|time=0.010647s;;;0.000000

OK - load average: 0.18, 0.72, 0.56|load1=0.180;10.000;15.000;0;load5=0.720;7.000;14.000;0; load15=0.560;4.000;8.000;0; 

WARNING - load average: 0.12, 0.66, 0.54|load1=0.120;0.000;15.000;0;load5=0.660;0.000;14.000;0; load15=0.540;0.000;8.000;0; 

CRITICAL - load average: 0.10, 0.64, 0.54|load1=0.100;0.000;0.000;0;load5=0.640;0.000;0.000;0; load15=0.540;0.000;0.000;0; 
```

**Comment by dav-m85** [comment]
Sounded quite like #100 :)
