### ISSUE TITLE
Add Logging to monitor bundle

### ISSUE THREAD

**Issue by alister** [liip/LiipMonitorBundle#126]
Would it be useful for others to add at least an option to log items at info, warning, and critical (via a PSR-3 interface) depending on the results of the checks?

Most of my own current monitoring/logging is built on logs, where exceptions or urgent events are sent to a service such as Rollbar and can then be also forwarded to Slack, PagerDuty and the like.

Currently, I'm thinking about adding an optional `Psr\Log\LoggerInterface` to the controller constructor (or via a a `setLog()` call, which would default to use a NullLogger. If you wished to override that with your own, to add a "@logger" service, you could do so.

**Comment by lsmith77** [comment]
@alister I am open to such a PR
