### ISSUE TITLE
Output from command line line always verbose despite --quiet

### ISSUE THREAD

**Issue by alister** [liip/LiipMonitorBundle#127]
I've just setup LiipMonitorBundle to run in a cronjob, as well as a regular HTTP check.  For the cronjob, the following command is being run:

```
bin/console --env=prod --quiet monitor:health --group=cli || echo liip_monitor failure
```

However, since it will always show output, even for all tests passing `OK`, the cronjob will always send an email. Is there a way to only display output when there is one or more tests in no-OK status (showing one test in failure/warning and multiple OKs would be fine).

I had expected having `--quiet` on the command line to allow for the option of not showing output when all tests are passing.

**Comment by lsmith77** [comment]
@alister this might need some work indeed .. basically someone needs to go through the commands .. should not be hard.

**Comment by alister** [comment]
It is not quite so easy - the output is being printed from within `ConsoleReporter`, but it always gets a brand new, and empty `ConsoleOutput` generated to use - and so does not know the verbosity status.

When the `$output` variable is injected (with a new `ConsoleReporter::setOutput()` call), there is no output at all with `--quiet`, because the write() is entirely suppressed.

I'm therefore going to use the verbosity flags to set an option that will suppress output of successful results on `--quiet`.
