### ISSUE TITLE
The callback Liip\MonitorBundle\Composer\ScriptHandler::checkHealth accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance

### ISSUE THREAD

**Issue by kniziol** [liip/LiipMonitorBundle#133]
**Full notice:**
`Deprecation Notice: The callback Liip\MonitorBundle\Composer\ScriptHandler::checkHealth declared at /vendor/liip/monitor-bundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:289`

**Command:**
> $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
(...)
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
Deprecation Notice: The callback Liip\MonitorBundle\Composer\ScriptHandler::checkHealth declared at /vendor/liip/monitor-bundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:289
Liip\MonitorBundle\Composer\ScriptHandler::checkHealth
Performing system health checks...
(...)

**Versions:**
- composer: 1.1.1 2016-05-17 12:25:44
- symfony/symfony: v3.0.6
- liip/monitor-bundle: 2.3.2

How to fix it?

**Comment by lsmith77** [comment]
can you look into a fix for this?
