### ISSUE TITLE
[Broken] Don't use asset.packages

### ISSUE THREAD

**Issue by cordoval** [liip/LiipMonitorBundle#149]
the controller uses assets.packages and is coupled

can i split the controllers into the main and then the others separate?

that way we can disable assets: false on symfony and still use this bundle

for now i will just shut down the controller and create my own controller 👍

**Comment by cordoval** [comment]
now on sf4.0 shutting down controllers does not work and fires exception

The service "liip_monitor.helper" has a dependency on a non-existent service "assets.packages".


(1/1) ServiceNotFoundExceptionThe service "liip_monitor.helper" has a dependency on a non-existent service "assets.packages".
--
in CheckExceptionOnInvalidReferenceBehaviorPass.php (line 32)
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(object(Reference), false)in AbstractRecursivePass.php (line 60)
at AbstractRecursivePass->processValue(array(object(Reference), object(Reference)), false)in CheckExceptionOnInvalidReferenceBehaviorPass.php (line 29)
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(array(object(Reference), object(Reference)))in AbstractRecursivePass.php (line 67)
at AbstractRecursivePass->processValue(object(Definition), true)in CheckExceptionOnInvalidReferenceBehaviorPass.php (line 29)
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(object(Definition), true)in AbstractRecursivePass.php (line 60)

**Comment by cordoval** [comment]
@lsmith77 https://github.com/liip/LiipMonitorBundle/pull/162

**Comment by lsmith77** [comment]
I tried to reproduce the issue on the symfony demo app and was not able to get the same error :-/

**Comment by lsmith77** [comment]
ah figured it out .. this happens with `assets: false`

**Comment by lsmith77** [comment]
I have an alternative fix https://github.com/liip/LiipMonitorBundle/pull/165
