### ISSUE TITLE
Feature request: Have an "all" option on the REST API

### ISSUE THREAD

**Issue by kvdnberg** [liip/LiipMonitorBundle#150]
We are using the health checks through the REST API in a monitoring tool. We'd like to check everything there, but we have grouped the checks to be able to check only parts on deploy.

Could the --all option somehow be added to the REST API so we can get all checks in one call?

**Comment by alister** [comment]
Maybe a group of groups? For example I have the groups 'quick' and 'cli'

```
liip_monitor:
    checks:
        groups:
            quick: # tests....
            cli:     # tests....
            all:
                groups: [quick, cli]
```

If a test was listed twice, you could just run the one in the first group, or both copies.
