### ISSUE TITLE
2.6.0 tag is broken, requires symfony/symfony ^4.0

### ISSUE THREAD

**Issue by iltar** [liip/LiipMonitorBundle#160]
2.6.0 has a dependency on `symfony/symfony ^4.0` while this is not present in the master.

https://github.com/liip/LiipMonitorBundle/blob/2.6.0/composer.json#L27-L32
https://github.com/liip/LiipMonitorBundle/blob/master/composer.json#L27-L31

**Comment by lsmith77** [comment]
https://github.com/liip/LiipMonitorBundle/releases/tag/2.6.1
