### ISSUE TITLE
Output is omitted when it is equivalent to boolean "false"

### ISSUE THREAD

**Issue by UlrichEckhardt** [liip/LiipMonitorBundle#170]
I have found a bug in the output, which occurs if the message part of a result can be interpreted as boolean false. This occurs in my case when I report a string `"0"` as message, which is then silently discarded.

The bug is in https://github.com/liip/LiipMonitorBundle/blob/6e46cdb73ea7600a4b947f1a3eaba09c4c4e6556/Helper/ConsoleReporter.php#L60, which tries to omit the colon when nothing follows. However, when I really want to output the string `'0'` there, that output is omitted, too. The check should be something like
```
$message = $result->getMessage();
if ($message != '') {
    $this->output->write(sprintf(': %s', $message));
}
```

Note that this change alone will have some undesired side effects due to another bug in AbstractResult. There, you have a member
```
    /**
     * @var string|null
     */
    protected $message;
```
and then a function to retrieve the message
```
    /**
     * Get message related to the result.
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }
```
which will happily return `null` in spite of the promised return type! So this needs to be fixed, too, in order to properly implement `ResultInterface`:
```
        return ($this->message === null) ? '' : $this->message;
```

**Comment by lsmith77** [comment]
can you submit a PR?
