### ISSUE TITLE
Support url for rabbitmq and redis

### ISSUE THREAD

**Issue by wizbit** [liip/LiipMonitorBundle#172]
In Symfony 4 bundles (possibly earlier), you can specify a url to connect to rabbitmq and redis, this is stored in a environment variable.

Currently I have to have that plus multiple environment variables of the url split into parts for this bundle.
Can we have the rabbitmq and redis monitors support a url connection.

Fixed in #171

**Comment by ndench** [comment]
Do we have an idea when a new release will be out that includes dsn support?
