### ISSUE TITLE
[BUG] v2.6.6 routing doesn't work with symfony 2.8

### ISSUE THREAD

**Issue by calinpristavu** [liip/LiipMonitorBundle#179]
The bundle's [routing](https://github.com/liip/LiipMonitorBundle/blob/master/Resources/config/routing.xml) doesn't work since tag 2.6.6 because of the double semicolons ::

v2.6.5 still uses single colon which works with sf2.8

Suggestion: either bump the sf requirement in v2.6.6 or adjust the routing

I'd be happy to submit a PR if you chose what to do :)

**Comment by cjprinse** [comment]
confirmed at symfony 3.4.12

**Comment by kbond** [comment]
This was caused by #178 

Not sure what is the best solution here. Perhaps a `legacy_routing.xml` and a note in the docs to use that with Symfony <4? What do you think @lsmith77?

**Comment by kbond** [comment]
Looks like any version <4.1 (does not work with 4.0)

**Comment by lsmith77** [comment]
oh .. then it basically means we would have to create a new major version so that we can still support all <4.1 versions that are still getting support .. or we just revert and accept deprecation notices :-/

**Comment by kbond** [comment]
Yeah.. no clean solution. A new major version would mean 2 branches to maintain as I don't think most people have upgraded to 4.1 yet.

**Comment by lsmith77** [comment]
yeah .. leaning towards revert .. bit surprised .. didn’t think it was common for Symfony to deprecate a feature without having supported the feature in at least one previous version.

**Comment by lsmith77** [comment]
so I guess the option of 2 routing files also exists .. now the question is who do we force to change? Symfony 4.1+ users or <4.1 users?

**Comment by Nyholm** [comment]
I would release a new patch release to revert the changes in the routing file. I would also create a new routing file that contains the SF4.1+ routes. (And also update the docs to refer to the new routing file)

**Comment by kbond** [comment]
What about reverting, then adding a routing.php file where we can do version checks. Then update the docs to use the PHP file going forward. Then there is at least a path to remove the deprecation.

**Comment by lsmith77** [comment]
yeah .. probably the best solution .. that way we can at least once <4.1 versions are EOL we can remove the old file and maintain a single php routing file going forward.

**Comment by kbond** [comment]
Ok, I will create a PR
