### ISSUE TITLE
[BUG] duplicated checks

### ISSUE THREAD

**Issue by cjprinse** [liip/LiipMonitorBundle#185]
I'm using tagged services with aliases for my custom checks.

Definition is like:
```xml
 <service id="Vendor\Bundles\AcaptureBundle\Check\AcaptureCheck">
            <argument type="service" id="acapture.settings.provider" />
            <tag name="liip_monitor.check" alias="acapture"/>
        </service>
```

Because of the alias, the check is added twice. Also, when using the group tag, this wil happen.
I think this is because of the autoconfiguration in LiipMonitorBundle::build

**Comment by kbond** [comment]
Does adding `autoconfigure="false"` to your service fix?

**Comment by cjprinse** [comment]
Thanks for your quick response.

Yes, this does fix the problem.
Maybe it's better to throw an exception when a service has multiple liip_monitor.check tags?

**Comment by jrjohnson** [comment]
Unless I'm missing something this makes it impossible to define a check that isn't in the default group. If I create a service like:

```
<?php

namespace App\Monitor;

use ZendDiagnostics\Check\CheckInterface;

class WritableFileSystem implements CheckInterface
{
...
}
```

even if I add a service definition:
```
services:
  App\Monitor\WritableFileSystem:
      tags:
      - { name: liip_monitor.check, group: production }
```

then you can see that I end up with *both* a service in the default group and one in the production group.

```
$ bin/console debug:container 'App\Monitor\WritableFileSystem'

Information for Service "App\Monitor\WritableFileSystem"
---------------- ---------------------------------------- 
  Option           Value                                   
 ---------------- ---------------------------------------- 
  Service ID       App\Monitor\WritableFileSystem          
  Class            App\Monitor\WritableFileSystem          
  Tags             liip_monitor.check (group: production)  
                   liip_monitor.check          
-------------------------- 
```

**Comment by kbond** [comment]
I think this can be closed now - any objections?
