### ISSUE TITLE
WARNING Security Advisory: Could not parse response from security advisory service.

### ISSUE THREAD

**Issue by jsbuilder** [liip/LiipMonitorBundle#200]
After update:
sensio/distribution-bundle (v5.0.22 => v5.0.23)
sensiolabs/security-checker (v4.1.8 => v5.0.1)

Performing system health checks...
WARNING Security Advisory: Could not parse response from security advisory service.

**Comment by kbond** [comment]
See https://github.com/zendframework/zend-diagnostics/pull/95

**Comment by lsmith77** [comment]
should be fixed https://github.com/zendframework/zend-diagnostics/releases/tag/v1.4.0
