### ISSUE TITLE
Incompatibility with latest Doctrine Migrations Library

### ISSUE THREAD

**Issue by stopfstedt** [liip/LiipMonitorBundle#202]
after upgrading to v2.0.0 of the [DoctrineMigrationsBundle](https://github.com/doctrine/DoctrineMigrationsBundle/releases/tag/v2.0.0), i'm getting an exception when clearing cache in my symfony application

```
In LiipMonitorExtension.php line 187:
                                                                     
  Please require at least "v1.1.0" of "Doctrine Migrations Library"  
                                                                     
```

Looking further into it, the namespace for the checked class has changed from `Doctrine\DBAL\Migrations\Configuration\Configuration` to `Doctrine\Migrations\Configuration\Configuration`.

**Comment by kbond** [comment]
fixed in 2.8.0
