### ISSUE TITLE
Missing parameters after update to Symfony 5

### ISSUE THREAD

**Issue by Knallcharge** [liip/LiipMonitorBundle#242]
Hi,

I just updated a project to Symfony 5 and got two errors with the monitor bundle concerning the "custom_error_pages"-checks:

1. You have requested a non-existent parameter "kernel.root_dir".
I can get rid of this by replacing "'%kernel.root_dir%'" with "'%kernel.project_dir%/src'" in my monitor.yaml.

2. You have requested a non-existent parameter "twig.exception_listener.controller".
Can't find a fix for this, %twig.exception_listener.controller% is also still listed in the documentation (https://github.com/liip/LiipMonitorBundle#full-default-config), is there some change needed to make this work with Symfony 5?

**Comment by kbond** [comment]
Indeed, this is broken now. Are your error pages located in the [documented](https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates) place for 5.1? 

`%kernel.project_dir%/templates/bundles/TwigBundle/Exception/`?

**Comment by Knallcharge** [comment]
Thanks for getting back. Yes, my error pages are at the right place (this hasn't changed since 4.4 which was my prior version: https://symfony.com/doc/4.4/controller/error_pages.html).

**Comment by kbond** [comment]
Hmm, and the check worked for you in 4.4?

**Comment by Knallcharge** [comment]
Yes.

**Comment by kbond** [comment]
Ok, looks like you may have been getting a false positive in 4.4 as the location is hard-coded in the check: https://github.com/liip/LiipMonitorBundle/blob/86865ca9aec9d93ef0ea7be9cd15d038f2c98dea/Check/CustomErrorPages.php#L64

I think https://github.com/liip/LiipMonitorBundle/blob/86865ca9aec9d93ef0ea7be9cd15d038f2c98dea/Check/CustomErrorPages.php#L60 must have been evaluating to false and always returning success...

**Comment by Knallcharge** [comment]
Sounds good.
