### ISSUE TITLE
Senseless setting of additional reporters, as in return always ArrayReport type

### ISSUE THREAD

**Issue by feosys** [liip/LiipMonitorBundle#244]
What sense of setting additional/custom reporters, if in return always fixed ArrayReporter? 

I have found it, when trying add custom reporter, which will also save additional data from \ZendDiagnostics\Result\AbstractResult::getData(). As ArrayReport does not do it.

https://github.com/liip/LiipMonitorBundle/blob/653b8578557385cf3fee4879d3bc3cb31d405020/Controller/HealthCheckController.php#L166

**Comment by kbond** [comment]
Sorry, I'm not too familiar with the controller or custom reporters but doesn't this line: 

https://github.com/liip/LiipMonitorBundle/blob/653b8578557385cf3fee4879d3bc3cb31d405020/Controller/HealthCheckController.php#L177

Set the additional reporters passed?

**Comment by feosys** [comment]
yes, you are right. But what sense of that additional reports, if in the end, in controller we return and use just default. 
For examle: 
i need change default report, and collect Result "data" (AbstractResult::getData()). Default ArrayReport doesn't collection it. How can i put my custom report implementation and return one more filed with liip rest api?

**Comment by kbond** [comment]
Oh I see, you're looking to *replace* the array reporter with your own. 

I think your best bet would be to extend the controller with your own implementation.

**Comment by feosys** [comment]
Yes,  u are right.
But anyway,  what purpose of that additional reporters,  if u could not use
their collected data (in the context of that controller)?

пн, 17 авг. 2020 г., 22:04 Kevin Bond <notifications@github.com>:

**Comment by kbond** [comment]
Ok, looked back and it looks like I was the one to add this feature - oops! In my defense it was 6 years ago - haha

Anyway, looks like it was added so the `MailReporter` could be used via the API... So not to change the output of the API, just to trigger some other reporter that does different things...

**Comment by feosys** [comment]
Aha,  I see.
Yeah,  in the context of the Mail reporter it has sense.
Thx a lot,  now I can see full picture.



пн, 17 авг. 2020 г., 22:31 Kevin Bond <notifications@github.com>:
