### ISSUE TITLE
Check for doctrine migrations does not work with doctrine/migrations v3

### ISSUE THREAD

**Issue by cgrabenstein** [liip/LiipMonitorBundle#246]
We are using the monitoring bundle together with doctrine/migrations v3 and it does not work for the following reasons:

The "autodiscovery" of the migration bundle fails, because the class that is being checked for, `Doctrine\Bundle\MigrationsBundle\Command\DoctrineCommand`, does not exist anymore.

If I provide a custom configuration file with the `configuration_file` option, the bundle tries to load the class `Doctrine\Migrations\Configuration\YamlConfiguration` which also does not exist anymore. 

Is there any plan to add support for v3?

**Comment by kbond** [comment]
Thanks for the issue @cgrabenstein - I think as a first step, we'd need https://github.com/laminas/laminas-diagnostics/issues/7 to be addressed.

**Comment by cgrabenstein** [comment]
I started a PR in the laminas project, but will need some help. Let's hope we get this done soon :-)

**Comment by lortuno** [comment]
I need to check in liip monitor if the migrations are up to date like I used to do before upgraing to version 3. Is this problem fixed yet? Why is the issue closed?

**Comment by kbond** [comment]
Reopened but still blocked by https://github.com/laminas/laminas-diagnostics/issues/7.

Hopefully, https://github.com/laminas/laminas-diagnostics/pull/10 will be merged and tagged soon.
