### ISSUE TITLE
Won't update to symfony 6.0 

### ISSUE THREAD

**Issue by jmads1** [liip/LiipMonitorBundle#266]
Symfony 5.4 works perfectly but does not allow updating to symfony 6.0. Could you incorporate it? Thank you very much.

> `
> Loading composer repositories with package information
> Restricting packages listed in "symfony/symfony" to "6.0.*"
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - liip/monitor-bundle[2.16.0, ..., 2.16.1] require symfony/framework-bundle ^3.4 || ^4.0 || ^5.0 -> found symfony/framework-bundle[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.34, v5.0.0, ..., v5.4.0] but it conflicts with your root composer.json require (6.0.*).
>     - Root composer.json requires liip/monitor-bundle ^2.16 -> satisfiable by liip/monitor-bundle[2.16.0, 2.16.1].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> `

**Comment by kbond** [comment]
Closed via #264.
