### ISSUE TITLE
Symfony6

### ISSUE THREAD

**Issue by Wordlesschunk** [liip/LiipMonitorBundle#278]
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/22942020/225571057-7f3581bb-8f65-4a8e-9c91-18d9fc0d7b1a.png">

Getting an error when trying to go to the route

I identified that the change made is within the 
HealthCheckController.php::142 
needs to be changed from  
`$reporters = $request->query->get('reporters') ?? [];` to `$reporters = $request->query->all('reporters') ?? [];`

**Comment by kbond** [comment]
Thanks for the report @Wordlesschunk, would you be able to create a PR?

**Comment by Wordlesschunk** [comment]
https://github.com/liip/LiipMonitorBundle/pull/279/commits/d11047257892cf56f1a74fb8f6b44f4af6aacbfa

**Comment by kbond** [comment]
Fixed via #279
