### ISSUE TITLE
Deprecation because of Symfony\Component\HttpKernel\DependencyInjection\Extension being internal since symfony 7.1

### ISSUE THREAD

**Issue by xammmue** [liip/LiipMonitorBundle#305]
The class Symfony\Component\HttpKernel\DependencyInjection\Extension (which gets extended in LiipMonitorExtension.php) was made internal in Symfony 7.1. This right now leads to a deprecation.

Symfony\Component\DependencyInjection\Extension\Extension may be used instead

**Comment by xammmue** [comment]
#306

**Comment by Chris53897** [comment]
thanks @xammmue 
Could you please close this issue as completed?

**Comment by xammmue** [comment]
Yes.
Thought I'd wait for a release but I can also just close already
