### ISSUE TITLE
Ember issue

### ISSUE THREAD

**Issue by ClementGautier** [liip/LiipMonitorBundle#76]
Hi,

I'm having the "Cannot perform operations on a Metamorph that is not in the DOM." issue. Its seems to be an Ember issue ( https://github.com/emberjs/ember.js/issues/1580 ) Could you update ember dependency / change the template to find a workaround ? 

This issue appears only if I configure health checks (if there is no checks I don't see the error). I'm not familiar with ember so I know that its probably not really helping but I tryied to remove the inner block of the `if Health.healthController.content.length` for test purpose and the error still appear.

I will create my own template anyway so you don't need to hurry.

**Comment by kbond** [comment]
Closing until we get more info.
