### ISSUE TITLE
Would be great to you scheduling capabilities ?

### ISSUE THREAD

**Issue by vishalmelmatti** [liip/LiipMonitorBundle#80]
This is really a nice bundle.

It would be great to have capability to run different  checks at different frequencies periodically. Might be something like  https://github.com/TDMobility/Symfony2TaskScheduler ?

**Comment by lsmith77** [comment]
Seems beyond the scope of the Bundle to me.
As you can group checks, you could easily use some scheduler to achieve what you want.
