### ISSUE TITLE
Provide a non-RESTful method for AWS health-check status

### ISSUE THREAD

**Issue by Bladrak** [liip/LiipMonitorBundle#90]
Hello,

I understand your point made in #2 ; however, when dealing with AWS health-check (see http://docs.aws.amazon.com/cli/latest/reference/elb/configure-health-check.html), you're not able to parse the response, only to react on the HTTP status code. 
What would you think about providing a new URL or a query param, which would give the status only through the response code? For instance, there could be a ``/monitor/health/elb_check`` which would reply a 200 when everything's OK, and a 502 when one or more checks failed.

What do you think about this?

**Comment by lsmith77** [comment]
hmm where in those docs do you see what kind of response it expects? didn't see anything on a quick skim. that being said, if you are right, yes I am open to add something for Amazon.

**Comment by Bladrak** [comment]
There it is (Output -> Health Check -> Target):
```
TCP is the default, specified as a TCP: port pair, for example "TCP:5000". In this case a healthcheck simply attempts to open a TCP connection to the instance on the specified port. Failure to connect within the configured timeout is considered unhealthy.
SSL is also specified as SSL: port pair, for example, SSL:5000.
For HTTP or HTTPS protocol, the situation is different. You have to include a ping path in the string. HTTP is specified as a HTTP:port;/;PathToPing; grouping, for example "HTTP:80/weather/us/wa/seattle". In this case, a HTTP GET request is issued to the instance on the given port and path. Any answer other than "200 OK" within the timeout period is considered unhealthy.
The total length of the HTTP ping target needs to be 1024 16-bit Unicode characters or less.
```

**Comment by lsmith77** [comment]
ok .. lets add it then

**Comment by Bladrak** [comment]
All right, I'm preparing a PR :)

**Comment by lsmith77** [comment]
not sure about the path yet .. ``/monitor/health/elb_check`` then again can't think of something sensible that is generic (ie. not elb specific)

**Comment by Bladrak** [comment]
Hmm maybe ``/monitor/health/http_status_check``?
