### ISSUE TITLE
Web Interface Screenshot broken

### ISSUE THREAD

**Issue by frne** [liip/LiipMonitorBundle#93]
In the README, the image of the web interface is broken.

**Comment by lsmith77** [comment]
@videlalvaro did you recently remove the file or kill your skitch.com account? then again, I guess we can just make a new screenshot ..

**Comment by videlalvaro** [comment]
Not at all. Probably skitch hosting wasn't the right place for the
screenshot.

**Comment by lsmith77** [comment]
added a new screenshot https://raw.githubusercontent.com/liip/LiipMonitorBundle/master/Resources/doc/screenshot.png
