### ISSUE TITLE
Backport for symfony 2.0/2.1

### ISSUE THREAD

**Issue by dav-m85** [liip/LiipMonitorBundle#95]
I backported tag 2.0.8 to be compatible with symfony 2.0 and 2.1. Can you consider creating a 1.1.x branch with the following developments ? https://github.com/lafourchette/LiipMonitorBundle/tree/1.1

I'm sure it could benefit to the community. One day we will migrate to newer version :)

**Comment by lsmith77** [comment]
while we actually do also have one client still on Symfony 2.0 .. I am not really sure it makes sense to maintain an official branch for that version. Especially due to the refactoring to ZF Diagnostics.

**Comment by lsmith77** [comment]
ah .. I see you made it compatible with ZF Diagnostics

**Comment by lsmith77** [comment]
can you open a PR on master so that I can get a sense of the differences?

**Comment by dav-m85** [comment]
PR open :)

**Comment by lsmith77** [comment]
closing based on the discussion in #96
