### ISSUE TITLE
List registered checks by aliases instead of labels

### ISSUE THREAD

**Issue by dav-m85** [liip/LiipMonitorBundle#98]
I find the monitor:list command quite disturbing, as it reports check labels instead of aliases. I would have thought it outputs something that can be used as an argument for the monitor:health command.
```bash
# current working
app/console monitor:list
  Restaurant to index count
  Reservation to process count
# this does not work
app/console monitor:health "Restaurant to index count"

# however this would be better IMHO
app/console monitor:list
  service.alias.check.restaurant_to_index
  service.alias.check.reservation_to_process
# works !
app/console monitor:health service.alias.check.reservation_to_process
```

**Comment by lsmith77** [comment]
makes sense. I guess we can change it to return <alias>: <description> ..

/cc @kbond

**Comment by kbond** [comment]
What about outputting both in a table?

**Comment by dav-m85** [comment]
Yes !

**Comment by lsmith77** [comment]
table sounds good too!

can you submit a PR @dav-m85 ?

**Comment by dav-m85** [comment]
Table it is. @lsmith77 Yes sure, I'm on it!

**Comment by dav-m85** [comment]
Guess it can be closed now.
