### ISSUE TITLE
Ability to list registered reporters

### ISSUE THREAD

**Issue by dav-m85** [liip/LiipMonitorBundle#99]
It would be nice to be able to list registered reporters like this:
```bash
app/console monitor:list reporters
  console
  array
  path
  raw-console
  swift-mailer

# then it would be easy to do
app/console monitor:health --reporter=array
```

**Comment by lsmith77** [comment]
+1

/cc @kbond

**Comment by kbond** [comment]
I'd prefer it to be a separate command or an option on `monitor:list` (ie `monitor:list --reporters`)

**Comment by lsmith77** [comment]
yeah ``monitor:list --reporters``

**Comment by lsmith77** [comment]
@dav-m85 can you submit a PR?

**Comment by dav-m85** [comment]
@lsmith77 yes sure! I started the issue to collect your feedbacks as a matter of fact, that way I'll submit something we agreed upon.
